import React from "react";
import { Link } from "react-router-dom";
import { UserAuth } from "../context/AuthContext";
import "./HomePage.css";

const TICKER_ITEMS = [
  "96.9 Crore Voters", "67.4% Turnout 2024", "543 Lok Sabha Seats",
  "28 States · 8 UTs", "Gemini AI Powered", "3 Features",
];

const FEATURES = [
  {
    num: "01",
    tag: "Gemini AI",
    title: "Consequence Analysis",
    desc: "What historically happens to development, GDP, and social indices when the ruling party stays vs. power changes hands — or when you don't vote at all.",
    link: "/consequences",
  },
  {
    num: "02",
    tag: "Data-driven",
    title: "Beat the Queue",
    desc: "Optimal voting hours based on historical turnout patterns so you spend minutes at the booth, not hours in line.",
    link: "/best-time",
  },
  {
    num: "03",
    tag: "ECI Data",
    title: "Voter Roll Shift",
    desc: "Track how the registered voter population has changed since the last election — new additions, deletions, net change.",
    link: "/voter-trends",
  },
];

const STATS = [
  { val: "96.9Cr", label: "Registered voters", cls: "hero__stat-val--saffron" },
  { val: "67.4%", label: "Turnout, 2024 General", cls: "" },
  { val: "543",   label: "Lok Sabha seats",      cls: "hero__stat-val--green" },
  { val: "28+8",  label: "States and UTs",       cls: "" },
];

const HomePage: React.FC = () => {
  const { user } = UserAuth();

  return (
    <main className="home">

      <section className="hero">
        <div className="hero__skybar" />
        <div className="hero__content">
          <div className="hero__left">
            <div className="hero__eyebrow">
              <span className="hero__dot" />
              India · Election Education · {new Date().getFullYear()}
            </div>

            <h1 className="hero__headline">
              <span className="hero__headline-top">Your</span>
              <span className="hero__headline-mid">VOTE</span>
              <span className="hero__headline-bot">Matters.</span>
            </h1>

            <p className="hero__sub">{("description")}</p>

            <div className="hero__cta-row">
              <Link to="/consequences" className="btn-primary">{("cta")}</Link>
              {!user && <Link to="/signin" className="btn-ghost">{("ctaSignIn")}</Link>}
            </div>
          </div>

          <div className="hero__right">
            {STATS.map((s) => (
              <div key={s.label} className="hero__stat">
                <div className={`hero__stat-val ${s.cls}`}>{s.val}</div>
                <div className="hero__stat-label">{s.label}</div>
              </div>
            ))}
          </div>
        </div>
        <div className="hero__big-text" aria-hidden="true">VAKKU</div>
      </section>

      <div className="ticker" aria-hidden="true">
        <div className="ticker__track">
          {[...TICKER_ITEMS, ...TICKER_ITEMS].map((text, i) => (
            <span key={i} className="ticker__item">
              {text} <span className="ticker__dot">·</span>
            </span>
          ))}
        </div>
      </div>

      <section className="features">
        <div className="features__header">
          <span className="features__eyebrow">What Vakku does</span>
          <h2 className="features__title">
            Know<br />before<br />you vote.
          </h2>
        </div>

        <div className="features__list">
          {FEATURES.map((f) => (
            <Link to={f.link} key={f.num} className="feature-item">
              <div className="feature-item__num">{f.num}</div>
              <div className="feature-item__body">
                <div className="feature-item__tag">{f.tag}</div>
                <h3 className="feature-item__title">{f.title}</h3>
                <p className="feature-item__desc">{f.desc}</p>
              </div>
              <div className="feature-item__arrow">→</div>
            </Link>
          ))}
        </div>
      </section>
      <section className="statement">
        <div className="statement__inner">
          <p className="statement__text">
            Does it look like your<br />vote doesn't matter?
          </p>
          <Link to="/consequences" className="btn-primary">See the evidence</Link>
        </div>
      </section>
      <div className="ai-section">
        <div className="ai-badge">
          <div className="ai-badge__left">
            <div className="ai-badge__label">Powered by</div>
            <div className="ai-badge__name">Gemini AI</div>
          </div>
          <p className="ai-badge__desc">
            Historical party analysis and development projections generated by Google's Gemini 1.5 Pro,
            grounded in real ECI electoral records and economic data from 1980 to present.
          </p>
        </div>
      </div>
      <footer className="footer">
        <div className="footer__inner">
          <div className="footer__logo">Vakku</div>
          <p className="footer__disc">{("Made with love for informed democracy.")}</p>
          <p className="footer__credit">{("@arnabiscoding")}</p>
        </div>
      </footer>

    </main>
  );
};

export default HomePage;
